# Generated by Django 4.2.7 on 2023-12-02 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 11, 26, 36, 813391, tzinfo=datetime.timezone.utc)),
        ),
    ]
